kind: pipeline
name: default
type: docker

steps:  
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build --no-cache -t oscarbot -f OscarBot/Dockerfile ./OscarBot

- name: clone-compose
  image: alpine/git
  environment:
    DEPLOYREPO:
      from_secret: DEPLOYREPO
  commands:
  - git clone $DEPLOYREPO

- name: deploy
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  #- apk add --no-cache py-pip
  # - pip install docker-compose
  - docker-compose -p oscarbot up -d

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
