version: "2"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "mssql"
    ports: 
      - 1433:1433
    environment:
      SA_PASSWORD: "${SQL_PASSWORD}"
      ACCEPT_EULA: "Y"  
    restart: unless-stopped
    volumes:
      - mssqldata:/var/opt/mssql
  bot:
    image: "oscarbot:latest"
    container_name: "oscarbot"
    environment:
      TZ: 'Europe/Copenhagen'
      token: ${DISCORD_TOKEN}
      OmdbKey: ${OMDB_KEY}  
      ConnectionString: "${SQL_CONNECTIONSTRING}"
    restart: unless-stopped    
volumes:
  mssqldata:
    external: true